apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-zone1
  labels:
    topology.kubernetes.io/zone: eastus-1
    app: nginx
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eastus-1
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/b0f09dd9-d94b-4334-a6aa-92ab69d65511/resourceGroups/MC_mjg-rg_mjg-aks_eastus/providers/Microsoft.Compute/disks/ssDisk1
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-zone2
  labels:
    topology.kubernetes.io/zone: eastus-2
    app: nginx
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eastus-2
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/b0f09dd9-d94b-4334-a6aa-92ab69d65511/resourceGroups/MC_mjg-rg_mjg-aks_eastus/providers/Microsoft.Compute/disks/ssDisk2
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-zone3
  labels:
    topology.kubernetes.io/zone: eastus-3
    app: nginx
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eastus-3
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/b0f09dd9-d94b-4334-a6aa-92ab69d65511/resourceGroups/MC_mjg-rg_mjg-aks_eastus/providers/Microsoft.Compute/disks/ssDisk3
    volumeAttributes:
      fsType: ext4